apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: marketplace
  namespace: openshift-marketplace
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
status:
  versions:
    - name: operator
      # The string "0.0.1-snapshot" is substituted by the CVO with the version of the payload
      version: "0.0.1-snapshot"
